spring.application.name=google-auth-backend
server.port=${SERVER_PORT:8081}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/google-auth-sample}

app.frontend-url=${FRONTEND_URL:http://localhost:5173}
app.google.client-id=${GOOGLE_CLIENT_ID:204296478750-lkigcs6506cbm5lsbp061rlj5313h0f1.apps.googleusercontent.com}
app.admin.email=${ADMIN_EMAIL:admin@gmail.com}
app.admin.default-password=${ADMIN_DEFAULT_PASSWORD:admin123}
app.technician.email=${TECHNICIAN_EMAIL:tech@gmail.com}
app.technician.default-password=${TECHNICIAN_DEFAULT_PASSWORD:tech123}
